# These are supported funding model platforms

github: [username] # Replace with your GitHub username
patreon: username # Replace with your Patreon username
open_collective: username # Replace with your Open Collective username
ko_fi: username # Replace with your Ko-fi username
tidelift: username # Replace with your Tidelift username
community_bridge: username # Replace with your Community Bridge username
liberapay: username # Replace with your Liberapay username
issuehunt: username # Replace with your IssueHunt username
otechie: username # Replace with your Otechie username
custom: https://example.com/donate # Replace with your custom donation link
